FROM puckel/docker-airflow:1.10.0-2
# Never prompts the user for choices on installation/configuration of packages

# Airflow
ARG AIRFLOW_VERSION=1.10.0
ARG AIRFLOW_HOME=/usr/local/airflow
ENV AIRFLOW_GPL_UNIDECODE yes

